enum tap_dance_codes {
  COPY_CUT,
  PASTE,
  MUTE_UNMUTE,
  UNDO,
  REDO,
  LAUNCH_PAUSE,
  LALT_LBRACK,
  LCTL_LPAREN,
  MAX_DANCES,
};

#include "dance_helpers.c" // This needs to be after tap_dance_codes because tap_dance_codes is used in the helpers

SINGLE_TAP__SINGLE_HOLD__DOUBLE_TAP__DOUBLE_HOLD(COPY_CUT, LCTL(KC_C), LCS(KC_C), LCTL(KC_X), LCS(KC_X))
SINGLE_TAP__SINGLE_HOLD(PASTE, LCTL(KC_V), LCS(KC_V))
SINGLE_TAP__DOUBLE_TAP(MUTE_UNMUTE, KC_F16, KC_F17)
SINGLE_TAP__SINGLE_HOLD(UNDO, LCTL(KC_Z), LCS(KC_Z))
SINGLE_TAP__SINGLE_HOLD(REDO, LCTL(KC_Y), LCS(KC_Y))
SINGLE_TAP__DOUBLE_TAP(LAUNCH_PAUSE, KC_MEDIA_PLAY_PAUSE, LALT(KC_SPACE))
SINGLE_TAP__SINGLE_HOLD(LALT_LBRACK, KC_LCBR, KC_LEFT_ALT)
SINGLE_TAP__SINGLE_HOLD(LCTL_LPAREN, KC_LPRN, KC_LEFT_CTRL)

tap_dance_action_t tap_dance_actions[MAX_DANCES] = {
  TAP_DANCE_ADVANCED(COPY_CUT),
  TAP_DANCE_ADVANCED(PASTE),
  TAP_DANCE_ADVANCED(MUTE_UNMUTE),
  TAP_DANCE_ADVANCED(UNDO),
  TAP_DANCE_ADVANCED(REDO),
  TAP_DANCE_ADVANCED(LAUNCH_PAUSE),
  TAP_DANCE_ADVANCED(LALT_LBRACK),
  TAP_DANCE_ADVANCED(LCTL_LPAREN),
};