name: Build
on:
  workflow_dispatch:

  push:
    branches:
      - main

  pull_request:
    branches:
      - main
jobs:
  build:
    name: Build
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/setup-python@v4.6.1
        with:
          python-version: "3.11.x"

      - uses: actions/checkout@v3.5.2

      - name: install CI python deps
        run: pip install -r .github/requirements.txt

      - name: build keymap
        run: make build

      - uses: actions/upload-artifact@v3.1.2
        with:
          name: moonlander_mcoding.bin
          path: qmk_firmware/.build/moonlander_mcoding.bin
          retention-days: 3
