name: Build
on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main
jobs:
  build:
    name: Build
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/setup-python@v2.2.2
        with:
          python-version: "3.x"

      - uses: actions/checkout@v2.3.4
        with:
          submodules: 'recursive'

      - name: install python deps
        run: pip install -r .github/requirements.txt

      - run: qmk setup -H $PWD -y

      - name: build keymap
        run: make moonlander:mcoding

      - uses: actions/upload-artifact@v2.2.3
        with:
          name: moonlander_mcoding.bin
          path: .build/moonlander_mcoding.bin
          retention-days: 3
