name: Sync Upstream
on:
  schedule:
    - cron: "0 10 * * 1"

  workflow_dispatch:

jobs:
  sync_with_upstream:
    runs-on: ubuntu-latest
    name: Sync main with upstream latest

    steps:
      - uses: actions/checkout@v2.3.4
        with:
          ref: main
          fetch-depth: 0
          submodules: "recursive"

      - name: checkout temp branch
        run: git switch -c upstream-sync

      - name: Pull upstream changes
        run: |
          git fetch https://github.com/zsa/qmk_firmware.git firmware20
          git merge FETCH_HEAD

      - name: open pull request
        id: cpr
        with:
          token: ${{ secrets.GH_PAT }}
          committer: "fsouzabot <fsouzabot@users.noreply.github.com>"
          author: "fsouzabot <fsouzabot@users.noreply.github.com>"
          base: main
          branch: upstream-sync
          delete-branch: true
          title: "Sync upstream"
          body: |
            Syncing commits from https://github.com/zsa/qmk_firmware.
          reviewers: fsouza

      - name: print PR information
        if: steps.cr.outputs.pull-request-number
        run: |
          echo "Pull Request Number - ${{ steps.cpr.outputs.pull-request-number }}"
          echo "Pull Request URL - ${{ steps.cpr.outputs.pull-request-url }}"
